export const OLD_SCHOOL_ACTIONS = {
  LOAD_RESTAURANTS_BEGIN: 'OLD_SCHOOL_ACTIONS_LOAD_RESTAURANTS_BEGIN',
  LOAD_RESTAURANTS_END: 'OLD_SCHOOL_ACTIONS_LOAD_RESTAURANTS_END',
  UPDATE_RESTAURANT_NAME: 'OLD_SCHOOL_ACTIONS_UPDATE_RESTAURANT_NAME',
  UPDATE_RESTAURANT_ADDRESS: 'OLD_SCHOOL_ACTIONS_UPDATE_RESTAURANT_ADDRESS',
  CREATE_RESTAURANT_BEGIN: 'OLD_SCHOOL_ACTIONS_CREATE_RESTAURANT_BEGIN',
  CREATE_RESTAURANT_END: 'OLD_SCHOOL_ACTIONS_CREATE_RESTAURANT_END'
};
